FROM ubuntu:22.04
LABEL maintainer="Polym <zjutpolym@gmail.com>"

RUN set -ex; \
  apt-get update -y; \
  DEBIAN_FRONTEND=noninteractive apt-get install -y \
    auditd \
    libelf1 \
    bpfcc-tools;

COPY entrypoint.sh /
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["/bin/bash"]
